flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    #Email is used for login
    title = StringField('Title',validators=[DataRequired()])
    content = TextAreaField('Content',validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import render_template,request,Blueprint
from flaskblog.models import Post,Recipe


main = Blueprint('main',__name__)

#routes are what we type into our browser to go to different pages
# =================================home =======================================
@main.route("/")
@main.route("/home")
def home():
    #default page is 1
    page = request.args.get('page',1,type=int)
    #amount of posts per page: per_page=5 and sort the results by date posted
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template('home.html',posts=posts)

@main.route("/recipe")
def home_recipe():
    #default page is 1
    page = request.args.get('page',1,type=int)
    #amount of posts per page: per_page=5 and sort the results by date posted
    recipes = Recipe.query.order_by(Recipe.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template('home_recipe.html',recipes=recipes)

# =================================about ======================================
@main.route("/about")
def about():
    return render_template('about.html',title='About')

flaskblog/posts/routes.py
from flask import render_template,request,Blueprint,flash,abort,url_for,redirect
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm
from flask_login import login_required,current_user

posts = Blueprint('posts',__name__)

#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Posts XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#=================== new post =================================================
@posts.route("/post/new",methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        #for auther the backref is used
        post = Post(title=form.title.data,content=form.content.data,author=current_user)
        #add the post to the database
        db.session.add(post)
        #commit the changes of the database
        db.session.commit()
        flash('Your post has been created!','success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post',form=form,legend='New Post')

#=========================== post =============================================
@posts.route("/post/<int:post_id>")
@login_required
def post(post_id):
    #get by id or give back a 404
    post = Post.query.get_or_404(post_id)
    return render_template('post.html',post=post,title=post.title)

#======================== update post =========================================
@posts.route("/post/<int:post_id>/update",methods=['GET','POST'])
@login_required
def update_post(post_id):
    #get by id or give back a 404
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        #403 is the http for forbidden route
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        #-----------------update the title and the content -----------------------
        post.title = form.title.data
        post.content = form.content.data
        #commit the changes to the database
        db.session.commit()
        # send a flash messge that the username or email was changed
        flash('Your post has been updated','success')
        #go back to account
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html',title='Update Post',form=form,legend='Update Post')

#====================== delete post ===========================================
@posts.route("/post/<int:post_id>/delete",methods=['POST'])
@login_required
def delete_post(post_id):
    #get by id or give back a 404
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        #403 is the http for forbidden route
        abort(403)
    else:
        #-----------------delete the post -----------------------
        db.session.delete(post)
        #commit the changes to the database
        db.session.commit()
        # send a flash messge that the post was deleted
        flash('Your post has been deleted','success')
        #go back to account
        return redirect(url_for('main.home'))

flaskblog/recipes/routes.py
from flask import render_template,request,Blueprint,flash,abort,url_for,redirect
from flaskblog import db
from flaskblog.models import Recipe
from flaskblog.recipes.forms import RecipeForm
from flask_login import login_required,current_user

recipes = Blueprint('recipes',__name__)

#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Recipes XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#=================== new recipe =================================================
@recipes.route("/recipe/new",methods=['GET','POST'])
@login_required
def new_recipe():
    form = RecipeForm()
    if form.validate_on_submit():
        #for auther the backref is used
        recipe = Recipe(title=form.title.data,content=form.content.data,author=current_user)
        #add the post to the database
        db.session.add(recipe)
        #commit the changes of the database
        db.session.commit()
        flash('Your recipe has been created!','success')
        print("das hier geht noch")
        return redirect(url_for('main.home_recipe'))
    return render_template('create_recipe.html',title='New Recipe',form=form,legend='New Recipe')

#=========================== recipe =============================================
@recipes.route("/recipe/<int:recipe_id>")
@login_required
def recipe(recipe_id):
    #get by id or give back a 404
    recipe = Recipe.query.get_or_404(recipe_id)
    return render_template('recipe.html',recipe=recipe,title=recipe.title)

#======================== update recipe =========================================
@recipes.route("/recipe/<int:recipe_id>/update",methods=['GET','POST'])
@login_required
def update_recipe(recipe_id):
    #get by id or give back a 404
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.author != current_user:
        #403 is the http for forbidden route
        abort(403)
    form = RecipeForm()
    if form.validate_on_submit():
        #-----------------update the title and the content -----------------------
        recipe.title = form.title.data
        recipe.content = form.content.data
        #commit the changes to the database
        db.session.commit()
        # send a flash messge that the username or email was changed
        flash('Your recipe has been updated','success')
        #go back to account
        return redirect(url_for('recipes.recipe',recipe_id=recipe.id))
    elif request.method == 'GET':
        form.title.data = recipe.title
        form.content.data = recipe.content
    return render_template('create_recipe.html',title='Update Recipe',form=form,legend='Update Recipe')

#====================== delete recipe ===========================================
@recipes.route("/recipe/<int:recipe_id>/delete",methods=['POST'])
@login_required
def delete_recipe(recipe_id):
    #get by id or give back a 404
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.author != current_user:
        #403 is the http for forbidden route
        abort(403)
    else:
        #-----------------delete the recipe -----------------------
        db.session.delete(recipe)
        #commit the changes to the database
        db.session.commit()
        # send a flash messge that the recipe was deleted
        flash('Your recipe has been deleted','success')
        #go back to account
        return redirect(url_for('main.home_recipe'))

flaskblog/users/routes.py
from flask_login import login_user,current_user,logout_user,login_required
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flaskblog.users.forms import (RegistrationForm,LoginForm,UpdateAccountForm,
                             RequestResetForm,ResetPasswordForm)
from flaskblog import bcrypt,db
from flaskblog.models import Post,User,Recipe
from flaskblog.users.utils import save_picture,send_reset_email

users = Blueprint('users',__name__)

#XXXXXXXXXXXXXXXXXXXXXXX User information and handling XXXXXXXXXXXXXXXXXXXXXXXX
# =================================register ===================================

@users.route("/register",methods=['GET','POST'])
def register():
    # --------------------this is what happens if already loged in ------------
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    # ------------------ do the registration stuff ----------------------------
    form = RegistrationForm()
    if form.validate_on_submit():
        #gnerate a hashed password form the input data form form, decode UTF makes a string in intead of bytes
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        #generate a user from the form data with the hashed password
        user = User(username=form.username.data,email=form.email.data,password=hashed_password)
        #add the user to the database
        db.session.add(user)
        #commit the changes of the database
        db.session.commit()
        #flash message pops up once
        #bootstrap has different allertstyles for succeses and warnings and errors
        #the flash function accepts a second argument which is the bootstrap name that the alert should have
        #dont forget to update the template to show the flash message
        flash(f'Your account has been created! Now you are able to login!','success')
        #after succesfull submit the user should be be redirected automatically to login
        return redirect(url_for('users.login'))
    return render_template('register.html',title='Register',form=form)

# =================================login =====================================
@users.route("/login",methods=['GET','POST'])
def login():
    # --------------------this is what happens if already loged in ------------
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    # ------------------ do the login stuff -----------------------------------
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        #if the user exists and the password is correct the user will be loged in
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            #for the login we use the extension of the loginmanager the login_user method
            #this is were we log in the user
            login_user(user,remember=form.remember.data)
            #next query
            # args is a dictionary which is accessed by the get method. 
            #if there is nothing the get method gives back a none
            #if it exists it is equal to the route
            next_page = request.args.get('next')
            #if succesfull redirect to the homepage
            return redirect (next_page) if next_page else redirect(url_for('main.home'))
        else:
            #flash message pops up once
            #bootstrap style <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
            #bootstrap has different allertstyles for succeses and warnings and errors
            #the flash function accepts a second argument which is the bootstrap name that the alert should have
            #dont forget to update the template to show the flash message
            flash('Unsuccessfull login. Please check email and password','danger')
    return render_template('login.html',title='Login',form=form)

# =================================logout =====================================
@users.route("/logout")
def logout():
    #this logs the user out
    #this does not take any arguments because it already knows that the user is loged in
    logout_user()
    # and redirects to the home page
    return redirect(url_for('main.home'))

# =================================account ====================================

#create a route for the user's account
@users.route("/account",methods=['GET','POST'])
#this extension makes sure the page is only displayed if the user is loged in
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        # ---------------- update the picture ---------------------------------
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        #-----------------update the user and the email -----------------------
        current_user.username = form.username.data
        current_user.email = form.email.data
        #commit the changes to the database
        db.session.commit()
        # send a flash messge that the username or email was changed
        flash('Your account has been updated','success')
        #go back to account
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static',filename='profile_pics/'+ current_user.image_file)
    return render_template('account.html',title='Account',image_file=image_file,form=form)

#=========================== sort post by user ================================   
@users.route("/user/<string:username>")
def user_content(username):
    #default page is 1
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username = username).first_or_404()
    #amount of posts per page: per_page=5 and sort the results by date posted
    posts = Post.query.filter_by(author = user).order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    recipes = Recipe.query.filter_by(author = user).order_by(Recipe.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template('user_content.html',posts=posts,user=user,recipes=recipes)


#====================== reset request =========================================
@users.route("/reset_password",methods=['GET','POST'])
def reset_request():   
    # --------------------this is what happens if already loged in --------
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user =User.query.filter_by(email=form.email.data).first()
        #now send the user a email
        send_reset_email(user)
        return redirect(url_for("users.login"))
        
    return render_template('reset_request.html',title='Reset Password',form=form)

#====================== reset token ===========================================
@users.route("/reset_password/<token>",methods=['GET','POST'])
def reset_token(token):   
    # --------------------this is what happens if already loged in ------------
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user=User.verifiy_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token','warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        #gnerate a hashed password form the input data form form, decode UTF makes a string in intead of bytes
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        user.password=hashed_password
        #commit the changes of the database
        db.session.commit()
        flash('Your password has been changed!','success')
        return redirect(url_for("users.login"))
    return render_template('reset_token.html',title='Reset Password',form=form)

flaskblog/wallbox/routes.py
from flask import render_template,Blueprint,request,flash,abort,url_for,redirect
#from flaskblog import db
#from flaskblog.models import Post
from flaskblog.wallbox.forms import SetCharginModeForm1,SetCharginModeForm2
from flask_login import login_required,current_user
from flaskblog import influxclient




wallbox = Blueprint('wallbox',__name__)

AllOW_CHARGINGMODES = [1,2,3]


#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX Posts XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#=================== new post =================================================
@wallbox.route("/setChargingMode",methods=['GET','POST'])
@login_required
def setChargingMode():
    form = SetCharginModeForm1()
    
    
    if form.validate_on_submit():
        #for auther the backref is used
        chargingMode = int(form.content.data)
        if chargingMode in AllOW_CHARGINGMODES:
            body = [{
                    "measurement": 'button',
                    "fields":
                        {"value": chargingMode}
                    }]
            influxclient.write_points(body, database='iobroker', time_precision='s', batch_size=10000, protocol='json')
            flash('Your charging mode has been set to {} by {}'.format(chargingMode,current_user),'success')
        else:
            flash('Mode {} is not allowed'.format(chargingMode,current_user),'danger')
    
        #return redirect(url_for('main.home'))
    return render_template('setChargingMode.html',form=form,legend='SetChargingMode')

flaskblog/templates/home.html
<!-- extends is a keyword that this document should be used by layout.html-->
{%extends"layout.html"%}
<!-- to be used it needs to be wraped in a content block-->
{%block content%}
    <!-- loop in html, posts is defined in flaskblog -->
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src={{url_for('static',filename='profile_pics/' + post.author.image_file)}}>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{url_for('users.user_content',username=post.author.username)}}">{{post.author.username}}</a>
                    <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
                </div>
                <div>
                <h2> <a class="article-title" href="{{url_for('posts.post',post_id=post.id)}}">{{post.title}}</a></h2>
                <p class="article-content">{{post.content}}</p>
                </div>
            </div>
        </article>
    {%endfor%}
    <!--left_edge: links on the left side, right_edge: links on the rigth edge, right_current includes the current page therefore 2 -->
    {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {%if page_num%}
            {%if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{url_for('main.home',page=page_num)}}">{{page_num}}</a>
            {%else%}
                <a class="btn btn-outline-info mb-4" href="{{url_for('main.home',page=page_num)}}">{{page_num}}</a>
            {%endif%}
        {%else%}
        ...
        {%endif%}
    {%endfor%}


{%endblock content%}

flaskblog/templates/layout.html
<!-- layout contains all the information which is the same for both pages -->
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- this controls how the website is displayed on different device-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
     <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- main.css wird hier integriert -->
    <!-- url_for will find the location for us-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='main.css')}}">
    
    <!-- if statement in html, title is defined in render_template of flaskblog -->
    {%if title %}
        <title>Flask Blog - {{title}}</title>
    {%else%}
        <title>Flask Blog</title>
    {%endif%}
</head>

<body>
    <!-- Navigation Bar -->
    <!-- automatic resize and so on.... -->
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Kerstin's Recipe Database</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
                        <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
                        <a class="nav-item nav-link" href="{{url_for('main.home_recipe')}}">Recipe</a>
                        
                    </div>
        <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{url_for('posts.new_post')}}">New Post</a>
                            <a class="nav-item nav-link" href="{{url_for('recipes.new_recipe')}}">New Recipe</a>
                            <a class="nav-item nav-link" href="{{url_for('wallbox.setChargingMode')}}">Wallbox</a>
                            <a class="nav-item nav-link" href="{{url_for('users.account')}}">Account</a>
                            <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                            <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
<!-- the other html will inherit this information and overwrite this section -->
    <main role="main" class="container">
    	<div class="row">
        	<div class="col-md-8">
        	<!-- show the flash message above the content-->
        	<!-- with_categories= true means that the agrument of flash can be accessed-->
        	<!-- get_flashed_messages: get the flashed message sent to this template-->
            	{% with messages = get_flashed_messages(with_categories=true) %}
                	<!-- if a flash messages exists --> 
                	{% if messages %}
                    	<!-- loop over the messages --> 
                    	{% for category,message in messages %}
                        	<div class="alert alert-{{category}}">
                        	<!-- and print the message-->
                            	{{message}}
                        	</div>
                    	{%endfor%}
                    {% endif %}
            	{% endwith %}
            	{% block content %}{% endblock content%}
        	</div>

    	</div>
	</main>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

flaskblog/templates/post.html
<!-- extends is a keyword that this document should be used by layout.html-->
{%extends"layout.html"%}
<!-- to be used it needs to be wraped in a content block-->
{%block content%}
    <article class="media content-section">
        <img class="rounded-circle article-img" src={{url_for('static',filename='profile_pics/' + post.author.image_file)}}>
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{url_for('users.user_content',username=post.author.username)}}">{{post.author.username}}</a>
                <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
                {%if post.author == current_user%}
                    <div>
                        <!-- bootstrap: a secondary button, make is small and give it some spacing (magin =1)  -->
                        <!-- mt: margin top, mb: margin bottom-->
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post',post_id=post.id)}}">Update Post</a>
                        <!-- now make the button for deleting, this leads to a modal, within the modal a form is generated -->
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {%endif%}
            </div>
            <div>
            <h2 class="article-title">{{post.title}}</h2>
            <p class="article-content">{{post.content}}</p>
            </div>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <!-- This makes a Post request to delete_post route as a submit button-->
            <form action="{{url_for('posts.delete_post',post_id=post.id)}}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>

{%endblock content%}

flaskblog/templates/recipe.html
<!-- extends is a keyword that this document should be used by layout.html-->
{%extends"layout.html"%}
<!-- to be used it needs to be wraped in a content block-->
{%block content%}
    <article class="media content-section">
        <img class="rounded-circle article-img" src={{url_for('static',filename='profile_pics/' + recipe.author.image_file)}}>
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{url_for('users.user_content',username=recipe.author.username)}}">{{recipe.author.username}}</a>
                <small class="text-muted">{{recipe.date_posted.strftime('%Y-%m-%d')}}</small>
                {%if recipe.author == current_user%}
                    <div>
                        <!-- bootstrap: a secondary button, make is small and give it some spacing (magin =1)  -->
                        <!-- mt: margin top, mb: margin bottom-->
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('recipes.update_recipe',recipe_id=recipe.id)}}">Update Recipe</a>
                        <!-- now make the button for deleting, this leads to a modal, within the modal a form is generated -->
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {%endif%}
            </div>
            <div>
            <h2 class="article-title">{{recipe.title}}</h2>
            <p class="article-content">{{recipe.content}}</p>
            </div>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Recipe?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <!-- This makes a recipe request to delete_recipe route as a submit button-->
            <form action="{{url_for('recipes.delete_recipe',recipe_id=recipe.id)}}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>

{%endblock content%}

flaskblog/templates/reset_request.html
<!-- extends is a keyword that this document should be used by layout.html-->
{%extends"layout.html"%}
<!-- to be used it needs to be wraped in a content block-->
{%block content%}
        <div class ="content-section">
            <form method ="POST" action="">
                    <!-- doble curlybraces: access variables through a template-->
        <!-- adding a csrf token or cross side request forgery token, this is part of the protection agains attacks-->
                {{form.hidden_tag()}}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Reset Password!</legend>

                    <div class ="form-group">
                        {{form.email.label(class="form-control-label")}}
                        <!-- only if we have errors -->
                        {%if form.email.errors%}
                            <!-- username field as it is and in case that it is invalid, add an invalid class tho that field-->
                            {{form.email(class="form-control from-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {%for error in form.email.errors%}
                                    <span>{{error}}</span>
                                {%endfor%}
                            </div>
                        {%else%}
                            {{form.email(class="form-control from-control-lg")}}
                        {%endif%}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{form.submit(class="btn btn-outline-info")}}
                </div>  
            </form>
    </div>
    <div class="border-top pt-3">
        <!-- small: kleiner text-->
        <small class="text-muted">
                                    <!-- a is an anchor tag -->
            Need an account? <a class="ml-2" href="{{url_for('users.register')}}">Sign up now!</a>
        </small>
    </div>
{%endblock content%}